version: '3'

volumes:
  production_postgres_data: {}

services:
  haskell:
    build:
      context: .
      dockerfile: compose/production/haskell/Dockerfile
    image: haskellchat_production_haskell
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.haskell
      - ./.envs/.production/.postgres
    ports:
      - "3000:3000"
    command: /start
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - prodution_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres